//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.17 at 02:11:07 PM CEST 
//


package pl.blaszak.microservice.session;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sessionState" type="{http://microservice.blaszak.pl/session}SessionState"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionState"
})
@XmlRootElement(name = "checkSessionResponse")
public class CheckSessionResponse {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected SessionState sessionState;

    /**
     * Gets the value of the sessionState property.
     * 
     * @return
     *     possible object is
     *     {@link SessionState }
     *     
     */
    public SessionState getSessionState() {
        return sessionState;
    }

    /**
     * Sets the value of the sessionState property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionState }
     *     
     */
    public void setSessionState(SessionState value) {
        this.sessionState = value;
    }

}
