//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.17 at 02:11:07 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://microservice.blaszak.pl/session", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.blaszak.microservice.session;
